//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 

namespace XmlSystem
{

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class HardwareConfig
    {

        private HardwareConfigMaxArbeitsbereich maxArbeitsbereichField;

        private byte einspannungsgrenzeField;

        private HardwareConfigWerkzeug[] werkzeugeField;

        private HardwareConfigWerkstueck[] werkstueckeField;

        /// <remarks/>
        public HardwareConfigMaxArbeitsbereich maxArbeitsbereich
        {
            get
            {
                return this.maxArbeitsbereichField;
            }
            set
            {
                this.maxArbeitsbereichField = value;
            }
        }

        /// <remarks/>
        public byte einspannungsgrenze
        {
            get
            {
                return this.einspannungsgrenzeField;
            }
            set
            {
                this.einspannungsgrenzeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("werkzeug", IsNullable = false)]
        public HardwareConfigWerkzeug[] werkzeuge
        {
            get
            {
                return this.werkzeugeField;
            }
            set
            {
                this.werkzeugeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("werkstueck", IsNullable = false)]
        public HardwareConfigWerkstueck[] werkstuecke
        {
            get
            {
                return this.werkstueckeField;
            }
            set
            {
                this.werkstueckeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HardwareConfigMaxArbeitsbereich
    {

        private ushort xField;

        private ushort yField;

        /// <remarks/>
        public ushort x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        public ushort y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HardwareConfigWerkzeug
    {

        private string breiteField;

        private sbyte arbeitshoeheField;

        private byte arbeitsgeschwindigkeitField;

        private byte fahrhoeheField;

        private byte fahrgeschwindigkeitField;

        private HardwareConfigWerkzeugBefestigungsposition befestigungspositionField;

        private string idField;

        /// <remarks/>
        public string Breite
        {
            get
            {
                return this.breiteField;
            }
            set
            {
                this.breiteField = value;
            }
        }

        /// <remarks/>
        public sbyte Arbeitshoehe
        {
            get
            {
                return this.arbeitshoeheField;
            }
            set
            {
                this.arbeitshoeheField = value;
            }
        }

        /// <remarks/>
        public byte Arbeitsgeschwindigkeit
        {
            get
            {
                return this.arbeitsgeschwindigkeitField;
            }
            set
            {
                this.arbeitsgeschwindigkeitField = value;
            }
        }

        /// <remarks/>
        public byte Fahrhoehe
        {
            get
            {
                return this.fahrhoeheField;
            }
            set
            {
                this.fahrhoeheField = value;
            }
        }

        /// <remarks/>
        public byte Fahrgeschwindigkeit
        {
            get
            {
                return this.fahrgeschwindigkeitField;
            }
            set
            {
                this.fahrgeschwindigkeitField = value;
            }
        }

        /// <remarks/>
        public HardwareConfigWerkzeugBefestigungsposition Befestigungsposition
        {
            get
            {
                return this.befestigungspositionField;
            }
            set
            {
                this.befestigungspositionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HardwareConfigWerkzeugBefestigungsposition
    {

        private sbyte xField;

        private sbyte yField;

        private sbyte zField;

        /// <remarks/>
        public sbyte x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        public sbyte y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        public sbyte z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class HardwareConfigWerkstueck
    {

        private byte dickeField;

        private string[] moegliche_WerkzeugeField;

        private string idField;

        /// <remarks/>
        public byte Dicke
        {
            get
            {
                return this.dickeField;
            }
            set
            {
                this.dickeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Werkzeug", IsNullable = false)]
        public string[] moegliche_Werkzeuge
        {
            get
            {
                return this.moegliche_WerkzeugeField;
            }
            set
            {
                this.moegliche_WerkzeugeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }


}